name: "shapeshift-dev"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "80:80"
    env_file: ./dev.env
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
  processor:
    build:
      context: .
      dockerfile: Dockerfile-processor
    env_file: ./dev.env
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"